services:
  sealskin:
    image: lscr.io/linuxserver/sealskin:latest
    container_name: sealskin

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - sealskin_config:/config
      - sealskin_storage:/storage

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PACKAGES=libfuse2|git|gdb
      # - RESTART_APP=true

      # - HOST_URL=IP|subdomain.doman.com #optional

    env_file:
      - ./sealskin/.env

    ports:
      - ${PORT:-4631}:3000
      - 5893:4398

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
