name: desktop-services

volumes:
  kali-linux_config:
    name: kali-linux_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/kali-linux/kali-linux_config

  sealskin_config:
    name: sealskin_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/sealskin/sealskin_config
  sealskin_storage:
    name: sealskin_storage
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/sealskin/sealskin_storage

  rustdesk_config:
    name: rustdesk_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/rustdesk/rustdesk_config

  remmina_config:
    name: remmina_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/remmina/remmina_config

  webtop_config:
    name: webtop_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/webtop/webtop_config

  kasm_config:
    name: kasm_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/kasm/kasm_config
  kasm_profiles:
    name: kasm_profiles
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/desktop-stack/kasm/kasm_profiles

networks:
  host:
  desktop-services:
    external: true
