name: openllm-vtuber-services

volumes:
  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs
  motioneye_shared:
    name: motioneye_shared
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/motioneye/motioneye_shared

networks:
  host:
  openllm-vtuber-services:
    external: true
