services:
  open-webui:
    image: ${IMAGE:-ghcr.io/open-webui/open-webui:main}
    container_name: ${NAME:-open-webui}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-apprise|linuxserver/mods:universal-cron|linuxserver/mods:universal-internationalization|linuxserver/mods:universal-stdout-logs|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - IMAGE_EDIT_MODEL=
      - IMAGE_GENERATION_MODEL=
      - COMFYUI_API_KEY=
      - COMFYUI_BASE_URL=http://${IP_ADDRESS:-192.168.1.2}:8188
      - COMFYUI_WORKFLOW=
      - DEFAULT_MODELS=
      - DEFAULT_USER_ROLE=pending
      - DEVICE_TYPE=cuda
      - DOCKER=true
      - ENABLE_IMAGE_EDIT=true
      - ENABLE_RAG_WEB_SEARCH=True
      - IMAGE_EDIT_ENGINE=comfyui
      - IMAGE_EDIT_SIZE=1024x1024
      - IMAGE_GENERATION_ENGINE=comfyui
      - IMAGE_SIZE=1024x1024
      - IMAGE_STEPS=30
      - IMAGE=ghcr.io/open-webui/open-webui:latest
      - IMAGES_EDIT_COMFYUI_API_KEY=
      - IMAGES_EDIT_COMFYUI_BASE_URL=http://${IP_ADDRESS:-192.168.1.2}:8188
      - IMAGES_EDIT_COMFYUI_WORKFLOW=
      - LIBRETRANSLATE_PORT=5000
      - NAME=open-webui
      - OLLAMA_BASE_URLS=${OLLAMA_BASE_URLS:-http://${IP_ADDRESS:-192.168.1.2}:11434}
      - PORT=${PORT:-8080}
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - SEARXNG_QUERY_URL="http://${IP_ADDRESS:-192.168.1.2}:8081/search?q=<query>"
      - USE_CUDA_DOCKER=true
      - USE_CUDA=true
      - VLLM_API_BASE=http://${IP_ADDRESS:-192.168.1.2}:3339

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - open-webui_data:/app/backend/data

    hostname: ${NAME:-open-webui}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - ${PORT:-8080}:8080

    env_file:
      - ./open-webui/.env

    deploy:
      replicas: 1

    extra_hosts:
      - host.docker.internal:host-gateway

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       curl,
    #       --silent,
    #       --fail,
    #       http://localhost:8080/health | jq -ne 'input.status == true' || exit 1,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    healthcheck:
      test: unset http_proxy;unset https_proxy;/usr/bin/curl --noproxy --fail --silent http://localhost:8080/health | jq -ne 'input.status == true'
      interval: 10s
      timeout: 5s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
