services:
  ferdium:
    image: lscr.io/linuxserver/ferdium:latest
    container_name: ferdium

    volumes:
      - ferdium_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PACKAGES=libfuse2|git|gdb
      # - RESTART_APP=true

    env_file:
      - ./ferdium/.env

    ports:
      - ${PORT:-5636}:3000
      - 3678:3001

    # shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
