services:
  ferdium:
    image: lscr.io/linuxserver/ferdium:latest
    container_name: ferdium

    volumes:
      - ferdium_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./ferdium/.env

    ports:
      - ${PORT:-5636}:3000
      - 3678:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
