services:
  dozzle:
    image: ${IMAGE:-ghcr.io/amir20/dozzle:latest}
    container_name: ${NAME:-dozzle}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - dozzle-app=true
      - dozzle

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8040}
      # - DOZZLE_MODE=swarm
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_AUTH_PROVIDER=simple


    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - dozzle_data:/data

    secrets:
      - DOZZLE_USERS:/data/users.yml
    
    hostname: ${NAME:-dozzle}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-8040}:8040

    env_file:
      - ./dozzle/.env

    deploy:
      replicas: 1
      mode: global

    tty: true

    stdin_open: true

    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
