services:
  altus:
    image: lscr.io/linuxserver/altus:latest
    container_name: altus

    volumes:
      - altus_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./altus/.env

    ports:
      - ${PORT:-4221}:3000
      - 3044:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
