services:
  webtop:
    # Tag	Available	Description
    # latest	✅	XFCE Alpine
    # alpine-i3	✅	i3 Alpine
    # alpine-kde	✅	KDE Alpine *Wayland Only
    # alpine-mate	✅	MATE Alpine
    # arch-i3	✅	i3 Arch
    # arch-kde	✅	KDE Arch
    # arch-mate	✅	MATE Arch
    # arch-xfce	✅	XFCE Arch
    # debian-i3	✅	i3 Debian
    # debian-kde	✅	KDE Debian
    # debian-mate	✅	MATE Debian
    # debian-xfce	✅	XFCE Debian
    # el-i3	✅	i3 Enterprise Linux
    # el-mate	✅	MATE Enterprise Linux
    # el-xfce	✅	XFCE Enterprise Linux
    # fedora-i3	✅	i3 Fedora
    # fedora-kde	✅	KDE Fedora
    # fedora-mate	✅	MATE Fedora
    # fedora-xfce	✅	XFCE Fedora
    # ubuntu-i3	✅	i3 Ubuntu
    # ubuntu-kde	✅	KDE Ubuntu
    # ubuntu-mate	✅	MATE Ubuntu
    # ubuntu-xfce	✅	XFCE Ubuntu

    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop

    volumes:
      - webtop_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PACKAGES=libfuse2|git|gdb
      # - RESTART_APP=true

    env_file:
      - ./webtop/.env

    ports:
      - ${PORT:-5312}:3000
      - 5741:3001

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
