services:
  signal:
    image: lscr.io/linuxserver/signal:latest
    container_name: signal

    volumes:
      - signal_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

    env_file:
      - ./signal/.env

    ports:
      - ${PORT:-4477}:3000
      - 5320:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
