services:
  airsonic-advanced:
    image: ${IMAGE:-lscr.io/linuxserver/airsonic-advanced:latest}
    container_name: ${NAME:-airsonic-advanced}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-4040}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro

      - airsonic-advanced_config:/config
      - airsonic-advanced_music:/music
      - airsonic-advanced_playlists:/playlists
      - airsonic-advanced_podcasts:/podcasts
      - airsonic-advanced_media:/media

    hostname: ${NAME:-airsonic-advanced}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-4040}:4040

    env_file:
      - ./airsonic-advanced/.env

    tty: true

    stdin_open: true

    deploy:
      replicas: 1

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-4040}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
