name: sdr-services

volumes:
  rtlsdrairband_config:
    name: rtlsdrairband_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/rtlsdrairband/rtlsdrairband_config

  openwebrxplus_config:
    name: openwebrxplus_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_config
  openwebrxplus_plugins:
    name: openwebrxplus_plugins
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_plugins
  openwebrxplus_var:
    name: openwebrxplus_var
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_var

  sdrangel-webtop_config:
    name: sdrangel-webtop_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/sdrangel-webtop/sdrangel-webtop_config

  rtl-tcp_config:
    name: rtl-tcp_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/rtl-tcp/rtl-tcp_config
      
networks:
  host:
  sdr-services:
    external: true

