services:
  steamos:
    image: ${IMAGE:-lscr.io/linuxserver/steamos}
    container_name: ${NAME:-steamos}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    cap_add:
      - NET_ADMIN

    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - DRINODE=/dev/dri/renderD128
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - PGID=${PGID:-1000}
      - PORT=${PORT:-3018}
      - PUID=${PUID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      # - HOST_IP=192.168.100.10
      # - RESOLUTION=1920x1080
      # - STARTUP=KDE

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - steamos_config:/config
      # - /dev/input:/dev/input
      # - /run/udev/data:/run/udev/data

    hostname: ${NAME:-steamos}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-3018}:3018
      - 3019:3019
      # - 27031-27036:27031-27036/udp
      # - 27031-27036:27031-27036
      # - 47984-47990:47984-47990
      # - 48010-48010:48010-48010
      # - 47998-48000:47998-48000/udp

    shm_size: 1gb

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    env_file:
      - ./steamos/.env

    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
      - /dev/uhid:/dev/uhid

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-3018}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
