services:
  gaseous-server:
    container_name: ${NAME:-gaseous-server}
    image: ${IMAGE:-gaseousgames/gaseousserver}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - dbhost=gaseous-server_mariadb
      - dbuser=root
      - dbpass=gaseous
      - igdbclientid=
      - igdbclientsecret=
      - PORT=${PORT:-5198}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - gaseous-server_data:/root/.gaseous-server

    hostname: ${NAME:-gaseous-server}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-5198}:80

    env_file:
      - ./gaseous-server/.env

    depends_on:
      - gaseous-server-mariadb

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-5198}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
  gaseous-server-mariadb:
    image: ${IMAGE:-mariadb}
    container_name: ${NAME:-gaseous-server-mariadb}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - MARIADB_USER=gaseous
      # - PORT=${PORT:-80}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - gaseous-server_mariadb:/var/lib/mysql

    hostname: ${NAME:-gaseous-server_mariadb}

    networks:
      host:
      media-services:

    # ports:
    #   - ${PORT:-80}:80

    secrets:
      - gaseous-server_mariadb_root_password
      - gaseous-server_mariadb_password

    env_file:
      - ./gaseous-server/.env

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-80}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
