services:
  romm:
    image: ${IMAGE:-rommapp/romm}
    container_name: ${NAME:-romm}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - DB_HOST=${DB_HOST:-romm-mariadb}
      - DB_NAME=${DB_NAME:-romm}
      - DB_USER=${DB_USER:-romm-user}
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED:-true}
      - PORT=${PORT:-8480}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - romm_library:/romm/library
      - romm_assets:/romm/assets
      - romm_config:/romm/config

    secrets:
      - romm_mariadb_password
      - romm_auth_secret_key
      - screenscraper_password
      - retroachievements_api_key
      - steamgriddb_api_key

    hostname: ${NAME:-romm}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-8480}:8480

    depends_on:
      romm-mariadb:
        condition: service_healthy
        restart: true

    env_file:
      - ./romm/.env

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-8080}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  romm-mariadb:
    image: ${IMAGE:-mariadb}
    container_name: ${NAME:-romm-mariadb}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-romm}
      - MARIADB_USER=${MARIADB_USER:-romm-user}
      - PORT=${PORT:-3306}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - romm_mariadb:/var/lib/mysql

    secrets:
      - romm_mariadb_root_password
      - romm_mariadb_password

    hostname: ${NAME:-romm-mariadb}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-3306}:3306

    env_file:
      - ./romm/.env

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
