services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina

    volumes:
      - remmina_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./remmina/.env

    ports:
      - ${PORT:-3431}:3000
      - 4962:4398

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
