services:
  kubepi:
    image: ${IMAGE:-1panel/kubepi}
    container_name: ${NAME:-kubepi}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - NODE_ENV=production
      - PORT=${PORT:-8483}
      # - NODE_IP=0.0.0.0
      # - NODE_PORT=8483

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

    hostname: ${NAME:-kubepi}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-8483}:80

    env_file:
      - ./kubepi/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://localhost:${PORT:-8483}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
