services:
  librechat:
    image: ${IMAGE:-ghcr.io/danny-avila/librechat-dev:latest}
    # pull_policy: always
    container_name: ${NAME:-librechat}
    restart: ${RESTART:-unless-stopped}

    extra_hosts:
      - host.docker.internal:host-gateway

    # build:
    #   context: ../../../DATA/ai-stack/librechat
    #   args:
    #     UID: ${PUID:-1000}
    #     GID: ${PGID:-1000}
    #   dockerfile: ./Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-3080}
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://librechat-mongodb:27017/librechat
      - MEILI_HOST=http://librechat-meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8002}
      - RAG_API_URL=http://librechat-rag-api:${RAG_PORT:-8002}
      - VLLM_API_BASE=http://vllm:3339

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - librechat_uploads:/app/uploads
      - librechat_models:/app/client/public/models
      - librechat_logs:/app/logs
      - librechat_output:/app/client/public/images

    hostname: ${NAME:-librechat}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - ${PORT:-3080}:3080

    env_file:
      - ./librechat/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # healthcheck:
    # test:
    #   [
    #     CMD,
    #     wget,
    #     --no-verbose,
    #     --tries=3,
    #     --spider,
    #     http://0.0.0.0:${PORT:-8082}/api/health,
    #   ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  librechat-mongodb:
    container_name: librechat-mongodb
    image: mongo
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - librechat_mongo_data:/data/db

    hostname: ${NAME:-librechat-mongodb}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    command: mongod --noauth

    env_file:
      - ./librechat/.env

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  librechat-meilisearch:
    container_name: librechat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - MEILI_HOST=http://librechat-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-xxxx}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - librechat_meili_data:/meili_data

    hostname: ${NAME:-librechat-meilisearch}

    user: ${PUID:-1000}:${PGID:-1000}

    env_file:
      - ./librechat/.env

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  librechat-vectordb:
    container_name: librechat-vectordb
    image: pgvector/pgvector:0.8.0-pg15-trixie
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - librechat_vectordb_data:/var/lib/postgresql/data

    env_file:
      - ./librechat/.env

    hostname: ${NAME:-librechat-vectordb}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  librechat-rag-api:
    container_name: librechat-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - DB_HOST=librechat-vectordb
      - RAG_PORT=${RAG_PORT:-8002}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - librechat-vectordb

    env_file:
      - ./librechat/.env

    hostname: ${NAME:-librechat-rag-api}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
