services:
  chroma:
    image: ${IMAGE:-chromadb/chroma}
    container_name: ${NAME:-chroma}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - CHROMA_DB_IMPL=${CHROMA_DB_IMPL:-clickhouse}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8124}

    # build:
    #   context: ../../../DATA/ai-stack/chroma
    #   dockerfile: ./Dockerfile

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - chroma_data:/chroma
      - chroma_index:/index_data

    # command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8004 --log-config log_config.yml

    networks:
      host:
      ai-services:

    env_file:
      - ./chroma/.env

    ports:
      - ${PORT:-8004}:8004

    depends_on:
      - clickhouse

    tty: true

    stdin_open: true

    healthcheck:
      test: [CMD, /bin/bash, -c, cat < /dev/null > /dev/tcp/localhost/8004]
      interval: 30s
      timeout: 10s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
