name: openllm-vtuber-services

volumes:

  openllm-vtuber_avatars:
    name: openllm-vtuber_avatars
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_avatars
  openllm-vtuber_backgrounds:
    name: openllm-vtuber_backgrounds
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_backgrounds
  openllm-vtuber_characters:
    name: openllm-vtuber_characters
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_characters
  openllm-vtuber_chat_history:
    name: openllm-vtuber_chat_history
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_chat_history
  openllm-vtuber_live2d-models:
    name: openllm-vtuber_live2d-models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_live2d-models
  openllm-vtuber_logs:
    name: openllm-vtuber_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_logs
  openllm-vtuber_prompts:
    name: openllm-vtuber_prompts
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_prompts
  openllm-vtuber_models:
    name: openllm-vtuber_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/openllm-vtuber-stack/openllm-vtuber-DATA/openllm-vtuber_models

networks:
  host:
  openllm-vtuber-services:
    external: true

