services:
  romm:
    # image: ${IMAGE:-t41372/open-llm-vtuber}
    image: ${IMAGE:-rommapp/romm:latest}
    container_name: ${NAME:-romm}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - DB_HOST=romm-database
      - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
      - DB_USER=romm-user # Should match MARIADB_USER in mariadb
      - DB_PASSWD=romm # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY= # Generate a key with `openssl rand -hex 32`
      - SCREENSCRAPER_USER=SgtStroopwafel # These are the recommended metadata providers
      - SCREENSCRAPER_PASSWORD= # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
      - RETROACHIEVEMENTS_API_KEY= # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
      - STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
      - HASHEOUS_API_ENABLED=true # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - romm_config:/romm/config # Path where config.yml is stored
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - romm_library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - romm_assets:/romm/assets # Uploaded saves, states, etc.

      - transmission_downloads:/downloads
      - transmission_watchfolder:/transmission_watchfolder

    hostname: ${NAME:-romm}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      testing-services:

    ports:
      - ${PORT:-4372}:8080

    env_file:
      - ./romm/.env

    # command:
    #   - -iwad /usr/share/romm/doom2.wad -file /usr/share/romm/DOOM_Infinite_098_PP2_H3.pk3

    # runtime: nvidia
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-12393}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    depends_on:
      romm-database:
        condition: service_healthy
        restart: true

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  romm-database:
    image: ${IMAGE:-mariadb:latest}
    container_name: ${NAME:-romm-database}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/l
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - MARIADB_ROOT_PASSWORD=romm # Use a unique, secure password
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=romm

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - romm_resources:/romm/resources
      - romm_redis_data:/redis/data
      - romm_library:/romm/library
      - romm_assets:/romm/assets
      - romm_config:/romm/config

    hostname: ${NAME:-romm-database}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      testing-services:

        # ports:
        #   - ${PORT:-5101}:5101

    env_file:
      - ./romm/.env

    # command:
    #   - -iwad /usr/share/romm/doom2.wad -file /usr/share/romm/DOOM_Infinite_098_PP2_H3.pk3

    # runtime: nvidia
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
