services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - kali-linux_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./kali-linux/.env

    ports:
      - ${PORT:-4824}:3000
      - 5839:301

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
