name: media-services

volumes:
  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs

  jellyseer_config:
    name: jellyseer_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/jellyseer/jellyseer_config

  audacity_config:
    name: audacity_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/audacity/audacity_config

  doplarr_config:
    name: doplarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/doplarr/doplarr_config

  ardour_config:
    name: ardour_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/ardour/ardour_config

  ombi_config:
    name: ombi_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/ombi/ombi_config

  prowlarr_config:
    name: prowlarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/prowlarr/prowlarr_config

  lidarr_config:
    name: lidarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_config
  lidarr_downloads:
    name: lidarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_downloads
  lidarr_music:
    name: lidarr_music
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_music

  radarr_config:
    name: radarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_config
  radarr_downloads:
    name: radarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_downloads
  radarr_movies:
    name: radarr_movies
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_movies

  sonarr_config:
    name: sonarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_config
  sonarr_downloads:
    name: sonarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_downloads
  sonarr_tvseries:
    name: sonarr_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_tvseries

  transmission_watchfolder:
    name: transmission_watchfolder
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/testing-stack/transmission/transmission_watchfolder
  transmission_downloads:
    name: transmission_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/testing-stack/transmission/transmission_downloads

networks:
  host:
  media-services:
    external: true
