name: media-services

volumes:
  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs

  jellyseer_config:
    name: jellyseer_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/jellyseer/jellyseer_config

  ombi_config:
    name: ombi_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/ombi/ombi_config

  prowlarr_config:
    name: prowlarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/prowlarr/prowlarr_config

networks:
  host:
  media-services:
    external: true
