services:
  sdrangel-webtop:
    # Version Tags:
    # This image provides various versions that are available via tags. Please read the descriptions carefully and exercise caution when using unstable or development tags.

    # Tag	Available	Description
    # latest	✅	XFCE Alpine
    # alpine-i3	✅	i3 Alpine
    # alpine-kde	✅	KDE Alpine *Wayland Only
    # alpine-mate	✅	MATE Alpine
    # arch-i3	✅	i3 Arch
    # arch-kde	✅	KDE Arch
    # arch-mate	✅	MATE Arch
    # arch-xfce	✅	XFCE Arch
    # debian-i3	✅	i3 Debian
    # debian-kde	✅	KDE Debian
    # debian-mate	✅	MATE Debian
    # debian-xfce	✅	XFCE Debian
    # el-i3	✅	i3 Enterprise Linux
    # el-mate	✅	MATE Enterprise Linux
    # el-xfce	✅	XFCE Enterprise Linux
    # fedora-i3	✅	i3 Fedora
    # fedora-kde	✅	KDE Fedora
    # fedora-mate	✅	MATE Fedora
    # fedora-xfce	✅	XFCE Fedora
    # ubuntu-i3	✅	i3 Ubuntu
    # ubuntu-kde	✅	KDE Ubuntu
    # ubuntu-mate	✅	MATE Ubuntu
    # ubuntu-xfce	✅	XFCE Ubuntu

    # image: ${IMAGE:-lscr.io/linuxserver/webtop:ubuntu-kde}
    container_name: ${NAME:-sdrangel-webtop}
    restart: ${RESTART:-unless-stopped}

    build:
      context: ../../../DATA/sdr-stack/sdrangel-webtop
      dockerfile: Dockerfile
      args:
        UID: ${PUID:-1000}
        GID: ${PGID:-1000}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      # - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/linuxserver/mods:universal-unrar6
      # # - DOCKER_HOST=
      # - INSTALL_PACKAGES=libfuse2|gdb|git
      # - RESTART_APP=true

      - SUBFOLDER=/ # Optioneel
      - TITLE=SDRAngel-Webtop

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      # - /var/run/docker.sock:/var/run/docker.sock

      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      # - /dev/bus/usb:/dev/bus/usb

      - sdrangel-webtop_config:/config

    hostname: ${NAME:-sdrangel-webtop}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      sdr-services:

    # command: [ sdrangel ]

    privileged: true

    ports:
      - ${PORT:-4448}:3000 # HTTP interface (KDE Desktop)
      - 3143:3001 # HTTPS interface
      - 3164:8091 # SDRangel REST API (voor externe apps)

    env_file:
      - ./sdrangel-webtop/.env

    healthcheck:
      disable: true

    devices:
      - /dev/video0:/dev/video0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/uinput:/dev/uinput
      - /dev/uhid:/dev/uhid
      - /dev/snd:/dev/snd
      - /dev/kmsg:/dev/kmsg
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset

    # device_cgroup_rules:
    #   - c 189:* rwm

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    shm_size: 1gb

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-12393}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

