services:
  webcord:
    image: lscr.io/linuxserver/webcord:latest
    container_name: webcord

    volumes:
      - webcord_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

    env_file:
      - ./webcord/.env

    ports:
      - ${PORT:-3188}:3000
      - 3938:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
