services:
  telegram:
    image: lscr.io/linuxserver/telegram:latest
    container_name: telegram

    volumes:
      - telegram_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./telegram/.env

    ports:
      - ${PORT:-3372}:3000
      - 4936:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
