services:
  autopulse:
    image: ${IMAGE:-ghcr.io/dan-online/autopulse}
    container_name: ${NAME:-autopulse}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - AUTOPULSE__APP__DATABASE_URL=postgres://postgres:autopulse@postgresql/autopulse
      - PORT=${PORT:-2885}
      - DEFAULT_SERVER_URL=http://0.0.0.0:2885
      # - FORCE_AUTH=true
      # - FORCE_DEFAULT_SERVER_URL=true
      # - FORCE_PASSWORD=true
      # - FORCE_SERVER_URL=true
      # - FORCE_USERNAME=true
      # - ORIGIN=https://mycool.domain

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    hostname: ${NAME:-autopulse}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-2885}:2885

    env_file:
      - ./autopulse/.env

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    healthcheck:
      test: CMD curl -f http://0.0.0.0:${PORT:-2885}/health
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
