services:
  rustdesk:
    image: lscr.io/linuxserver/rustdesk:latest
    container_name: rustdesk

    volumes:
      - rustdesk_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./rustdesk/.env

    ports:
      - ${PORT:-5571}:3000
      - 4824:4398

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
