services:
  viewtube:
    image: ${IMAGE:-mauriceo/viewtube:latest}
    container_name: ${NAME:-viewtube}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/media-stack/viewtube

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8066}
      - VIEWTUBE_DATABASE_HOST=${VIEWTUBE_DATABASE_HOST:-viewtube-mongodb}
      - VIEWTUBE_REDIS_HOST=${VIEWTUBE_REDIS_HOST:-viewtube-redis}
      # - VIEWTUBE_ADMIN_USER=${VIEWTUBE_ADMIN_USER:-admin}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - viewtube_data:/data

    hostname: ${NAME:-viewtube}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-8066}:8066

    env_file:
      - ./viewtube/.env

    depends_on:
      - viewtube-mongodb
      - viewtube-redis

    deploy:
      replicas: 1

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://0.0.0.0:${PORT:-8066}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  viewtube-mongodb:
    image: mongo:latest
    container_name: ${NAME:-viewtube-mongodb}

    ports:
      - 27018:27017

    networks:
      host:
      media-services:

  viewtube-redis:
    image: redis:latest
    container_name: ${NAME:-viewtube-redis}

    networks:
      host:
      media-services:
