name: books-services

volumes:
  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  calibre-web_data:
    name: calibre-web_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre-web/calibre-web_data
  calibre-web_library:
    name: calibre-web_library
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre-web/calibre-web_library

  calibre_books:
    name: calibre_books
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre/calibre_books
  calibre_autoadd:
    name: calibre_autoadd
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre/calibre_autoadd
  calibre_config:
    name: calibre_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre/calibre_config
  calibre_library:
    name: calibre_library
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/calibre/calibre_library

  cops_config:
    name: cops_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/cops/cops_config
  cops_books:
    name: cops_books
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/cops/cops_books

  mylar3_config:
    name: mylar3_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/mylar3/mylar3_config
  mylar3_comics:
    name: mylar3_comics
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/mylar3/mylar3_comics
  mylar3_downloads:
    name: mylar3_downloads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/mylar3/mylar3_downloads

  lazylibrarian_data:
    name: lazylibrarian_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/lazylibrarian/lazylibrarian_data
  lazylibrarian_downloads:
    name: lazylibrarian_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/lazylibrarian/lazylibrarian_downloads
  lazylibrarian_library:
    name: lazylibrarian_library
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/lazylibrarian/lazylibrarian_library

  kavita_data:
    name: kavita_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/kavita/kavita_data
  kavita_library:
    name: kavita_library
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/kavita/kavita_library

  ubooquity_data:
    name: ubooquity_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/ubooquity/ubooquity_data
  ubooquity_library:
    name: ubooquity_library
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/ubooquity/ubooquity_library
  ubooquity_comics:
    name: ubooquity_comics
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/ubooquity/ubooquity_comics
  ubooquity_rawfiles:
    name: ubooquity_rawfiles
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/books-stack/ubooquity/ubooquity_rawfiles

  transmission_watchfolder:
    name: transmission_watchfolder
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/downloader-stack/transmission/transmission_watchfolder
  transmission_downloads:
    name: transmission_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/downloader-stack/transmission/transmission_downloads

networks:
  host:
  books-services:
    external: true
