services:
  homarr:
    image: ${IMAGE:-ghcr.io/homarr-labs/homarr:latest}
    container_name: ${NAME:-homarr}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-7575}
      - HOMARR_DEFAULT_STOP_TIMEOUT=${HOMARR_DEFAULT_STOP_TIMEOUT:-10}
      - HOMARR_INTERVAL=${HOMARR_INTERVAL:-5}
      - HOMARR_ONLY_MONITOR_RUNNING=${HOMARR_ONLY_MONITOR_RUNNING:-false}
      - HOMARR_START_PERIOD=${HOMARR_START_PERIOD:-0}
      - DOCKER_HOSTNAMES=${DOCKER_HOSTNAMES:-localhost}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY:-}
      - HOMARR_CONTAINER_LABEL=${HOMARR_CONTAINER_LABEL:-homarr}
      - DOCKER_PORTS=${DOCKER_PORTS:-}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - homarr_appdata:/appdata

    hostname: ${NAME:-homarr}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-7575}:7575

    env_file:
      - ./homarr/.env

    deploy:
      replicas: 1

    tty: true

    stdin_open: true

    # healthcheck:
    #   test: CMD curl -f http://localhost:${PORT:-7575}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
