services:
  better-chatbot:
    image: ${IMAGE:-globalspec/better-chatbot:latest}
    # pull_policy: always
    container_name: ${NAME:-better-chatbot}
    restart: ${RESTART:-unless-stopped}

    user: ${PUID:-1000}:${PGID:-1000}

    extra_hosts:
      - host.docker.internal:host-gateway

    # build:
    #   context: ../../../DATA/ai-stack/better-chatbot
    #   args:
    #     UID: ${PUID:-1000}
    #     GID: ${PGID:-1000}
    #   dockerfile: ./Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-3080}
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://better-chatbot-mongodb:27017/better-chatbot
      - MEILI_HOST=http://better-chatbot-meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://better-chatbot-rag-api:${RAG_PORT:-8000}
      - VLLM_API_BASE=http://vllm:3339

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - better-chatbot_images:/app/client/public/images
      - better-chatbot_uploads:/app/uploads
      - better-chatbot_logs:/app/logs

    hostname: ${NAME:-better-chatbot}

    networks:
      host:
      ai-services:

    ports:
      - ${PORT:-3080}:3080

    env_file:
      - ./better-chatbot/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # healthcheck:
    # test:
    #   [
    #     CMD,
    #     wget,
    #     --no-verbose,
    #     --tries=3,
    #     --spider,
    #     http://localhost:${PORT:-8082}/api/health,
    #   ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  better-chatbot-mongodb:
    container_name: better-chatbot-mongodb
    image: mongo
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PGID:-1000}:${PUID:-1000}

    networks:
      host:
      ai-services:

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - better-chatbot_mongo_data:/data/db

    command: mongod --noauth

    env_file:
      - ./better-chatbot/.env

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  better-chatbot-meilisearch:
    container_name: better-chatbot-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always

    user: ${PGID:-1000}:${PUID:-1000}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - MEILI_HOST=http://better-chatbot-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-xxxx}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - better-chatbot_meili_data:/meili_data

    env_file:
      - ./better-chatbot/.env

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  better-chatbot-vectordb:
    container_name: better-chatbot-vectordb
    image: pgvector/pgvector:0.8.0-pg15-trixie
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - better-chatbot_vectordb_data:/var/lib/postgresql/data

    env_file:
      - ./better-chatbot/.env

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  better-chatbot-rag-api:
    container_name: better-chatbot-rag-api
    image: ghcr.io/danny-avila/better-chatbot-rag-api-dev-lite:latest
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - DB_HOST=better-chatbot-vectordb
      - RAG_PORT=${RAG_PORT:-8000}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - better-chatbot-vectordb

    env_file:
      - ./better-chatbot/.env

    networks:
      host:
      ai-services:

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
