services:
  dockge:
    container_name: ${NAME:-dockge}
    image: ${IMAGE:-louislam/dockge}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=../../../STACKS
      - PORT=${PORT:-5001}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - dockge_data:/app/data
      - ../../../STACKS:/opt/stacks
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)

    hostname: ${NAME:-dockge}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-5001}:5001

    env_file:
      - ./dockge/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://localhost:${PORT:-5001}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
