services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon

    volumes:
      - mastodon_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - LOCAL_DOMAIN=example.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=
      - SECRET_KEY_BASE=
      - OTP_SECRET=
      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=
      - SMTP_SERVER=mail.example.com
      - SMTP_PORT=25
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - SMTP_FROM_ADDRESS=notifications@example.com
      - S3_ENABLED=false
      # optional
      # - WEB_DOMAIN=mastodon.example.com
      # - ES_HOST=es
      # - ES_PORT=9200
      # - ES_USER=elastic
      # - ES_PASS=elastic
      # - S3_BUCKET=
      # - AWS_ACCESS_KEY_ID=
      # - AWS_SECRET_ACCESS_KEY=
      # - S3_ALIAS_HOST=
      # - SIDEKIQ_ONLY=false
      # - SIDEKIQ_QUEUE=
      # - SIDEKIQ_DEFAULT=false
      # - SIDEKIQ_THREADS=5
      # - DB_POOL=5
      # - NO_CHOWN=
      # - MASTODON_PROMETHEUS_EXPORTER_ENABLED=

    env_file:
      - ./mastodon/.env

    ports:
      - ${PORT:-4477}:80
      - 5320:443

      # optional
      - 9394:9394

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
