services:
  gamevault:
    # image: ${IMAGE:-t41372/open-llm-vtuber}
    image: ${IMAGE:-phalcode/gamevault-backend:latest}
    container_name: ${NAME:-gamevault}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - DB_HOST=gamevault-database
      - DB_NAME=gamevault # Should match MARIADB_DATABASE in mariadb
      - DB_USERNAME=gamevault # Should match MARIADB_USER in mariadb
      - DB_PASSWORD=gamevault # Should match MARIADB_PASSWORD in mariadb

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - gamevault_files:/files # Path where config.yml is stored
      - gamevault_media:/media # Resources fetched from IGDB (covers, screenshots, etc.)

      - transmission_downloads:/downloads
      - transmission_watchfolder:/transmission_watchfolder

    hostname: ${NAME:-gamevault}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      testing-services:

    ports:
      - ${PORT:-3253}:8080

    env_file:
      - ./gamevault/.env

    # command:
    #   - -iwad /usr/share/gamevault/doom2.wad -file /usr/share/gamevault/DOOM_Infinite_098_PP2_H3.pk3

    # runtime: nvidia
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-12393}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  gamevault-database:
    image: ${IMAGE:-postgres:latest}
    container_name: ${NAME:-gamevault-database}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/l
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - POSTGRES_USER=gamevault
      - POSTGRES_PASSWORD=gamevault
      - POSTGRES_DB=gamevault

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - gamevault_data:/var/lib/postgresql/data

    hostname: ${NAME:-gamevault-database}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      testing-services:

        # ports:
        #   - ${PORT:-5101}:5101

    env_file:
      - ./gamevault/.env

    # command:
    #   - -iwad /usr/share/gamevault/doom2.wad -file /usr/share/gamevault/DOOM_Infinite_098_PP2_H3.pk3

    # runtime: nvidia
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
    #   start_period: 30s
    #   start_interval: 10s
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
