name: airi-services

networks:
  host:
  airi-services:
    external: true

volumes:
  airi_data:
    name: airi_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/airi-stack/airi/airi_data
