name: sdr-services

volumes:
  rtlsdrairband_config:
    name: rtlsdrairband_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/rtlsdrairband/rtlsdrairband_config

  openwebrxplus_config:
    name: openwebrxplus_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_config
  openwebrxplus_plugins:
    name: openwebrxplus_plugins
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_plugins
  openwebrxplus_var:
    name: openwebrxplus_var
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/sdr-stack/openwebrxplus/openwebrxplus_var

networks:
  host:
  sdr-services:
    external: true
