services:
  vesselalert:
    image: ${IMAGE:-ghcr.io/sdr-enthusiasts/docker-vesselalert:latest}
    container_name: ${NAME:-vesselalert}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-apprise|linuxserver/mods:universal-git|linuxserver/mods:universal-tshoot|linuxserver/mods:universal-apprise|linuxserver/mods:universal-cron|linuxserver/mods:universal-internationalization|linuxserver/mods:universal-stdout-logs|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - AIS_URL=http://shipfeeder
      - CHECK_INTERVAL=30
      - MASTODON_SERVER=airwaves.social
      - MASTODON_ACCESS_TOKEN=${VESSELALERT_MASTODON_TOKEN}
      - MASTODON_SKIP_FILTER=^[9]{2}[0-9]{7}$|^[0-9]{7}$
      - MASTODON_MIN_DIST=10
      - NOTIFICATION_MIN_DIST=10
      - MASTODON_CUSTOM_FIELD=${VESSELALERT_MASTODON_CUSTOM_FIELD}
      - MASTODON_LINK_SHIPXPLORER=on
      - MASTODON_LINK_MARINETRAFFIC=on
      - MASTODON_LINK_VESSELFINDER=on
      - MASTODON_ONLY_NEW_ON_STARTUP=on
      - MASTODON_THROTTLE=on
      - NOTIFICATION_MAPURL=on
      - DISCORD_NAME=${VESSELALERT_DISCORD_NAME}
      - DISCORD_AVATAR_URL=${VESSELALERT_AVATAR_URL}
      - DISCORD_WEBHOOKS=${VESSELALERT_DISCORD_WEBHOOKS}
      - SCREENSHOT_URL=http://ais-screenshot:5042

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - /dev/bus/usb:/dev/bus/usb

      - vesselalert_data:/data

    hostname: ${NAME:-vesselalert}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      sdr-services:


    tmpfs:
      - /tmp

    # ports:
    #   - ${PORT:-8073}:80
    #   - 9988:9988/udp

    env_file:
      - ./vesselalert/.env

    healthcheck:
      disable: true

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/uinput
      # - /dev/uhid
      # - /dev/snd
      # - /dev/kmsg



    # device_cgroup_rules:
    #   - c 189:* rwm

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, compute, video, graphics, utility ]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-12393}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
