services:
  beszel:
    image: ${IMAGE:-henrygd/beszel:latest}
    container_name: ${NAME:-beszel}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8890}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket

    hostname: ${NAME:-beszel}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-8890}:8890

    env_file:
      - ./beszel/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://0.0.0.0:${PORT:-8890}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: ${NAME:-beszel-agent}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - HUB_URL=http://0.0.0.0:8890
      - LISTEN=/beszel_socket/beszel.sock
      - KEY=key
      - TOKEN=token

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - beszel_agent_data:/beszel_agent_data
      - beszel_socket:/beszel_socket

    hostname: ${NAME:-beszel-agent}

    # network_mode: host

    networks:
      host:
      essential-services:

    # ports:
    #   - ${PORT:-8890}:8890

    env_file:
      - ./beszel/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://0.0.0.0:${PORT:-7578}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
