services:
  clickhouse:
    image: ${IMAGE:-clickhouse/clickhouse-server:latest}
    container_name: ${NAME:-clickhouse}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PUID:-1000}:${PGID:-1000}

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - CLICKHOUSE_TCP_PORT=${CLICKHOUSE_TCP_PORT:-9000}
      - CLICKHOUSE_HTTP_PORT=${PORT:-8124}
      - STORAGE_DIR=${STORAGE_DIR:-/app/server/storage}
      # - CLICKHOUSE_RUN_AS_ROOT=${CLICKHOUSE_RUN_AS_ROOT:-1}
      # - CLICKHOUSE_DB=${CLICKHOUSE_DB:-clickhouse}
      # - CLICKHOUSE_USER=${CLICKHOUSE_USER:-clickhouse}
      # - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:-1}
      # - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-clickhouse}
      # - CLICKHOUSE_SKIP_USER_SETUP=${CLICKHOUSE_SKIP_USER_SETUP:-1}

    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK

    ports:
      - ${PORT:-8124}:8124
      - 9000:9000
      - 9363:9363

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - clickhouse_backups:/var/lib/clickhouse/backups
      - clickhouse_configs:/etc/clickhouse-server/config.d
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_initdb:/docker-entrypoint-initdb.d
      - clickhouse_logs:/var/log/clickhouse-server/
      - clickhouse_users:/etc/clickhouse-server/users.d
      # - ../../../DATA/ai-stack/clickhouse/config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      # - ../../../DATA/ai-stack/chroma/config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml

    networks:
      host:
      ai-services:

    env_file:
      - ./clickhouse/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test: [CMD, clickhouse-client, --query, SELECT 1]
      # test: wget --no-verbose --tries=1 --spider http://localhost:8124/?query=SELECT%201 || exit 1

    depends_on:
      - minio
      - minio-bucket-creator

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
