name: arr-services

networks:
  host:
  arr-services:
    external: true

volumes:
  autobrr_config:
    name: autobrr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/autobrr/autobrr_config

  bazarr_config:
    name: bazarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/bazarr/bazarr_config
  bazarr_media:
    name: bazarr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/bazarr/bazarr_media

  buildarr_config:
    name: buildarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/buildarr/buildarr_config

  calendarr_custom_footers:
    name: calendarr_custom_footers
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/calendarr/calendarr_custom_footers
  calendarr_logs:
    name: calendarr_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/calendarr/calendarr_logs

  checkrr_config:
    name: checkrr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/checkrr/checkrr_config/checkrr.yaml
  checkrr_data:
    name: checkrr_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/checkrr/checkrr_data/checkrr.db
  checkrr_media:
    name: checkrr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/checkrr/media

  dasharr_config:
    name: dasharr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/dasharr/dasharr_config

  flemmarr_config:
    name: flemmarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/flemmarr/flemmarr_config

  jellyseerr_appdata:
    name: jellyseerr_appdata
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/jellyseerr/jellyseerr_appdata
  jellyseerr_config:
    name: jellyseerr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/jellyseerr/jellyseerr_config

  kapowarr_db:
    name: kapowarr_db
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/kapowarr/kapowarr_db
  kapowarr_downloads:
    name: kapowarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/kapowarr/kapowarr_downloads
  kapowarr_comics_folder:
    name: kapowarr_comics_folder
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/kapowarr/kapowarr_comics_folder

  lidarr_config:
    name: lidarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/lidarr/lidarr_config
  lidarr_media:
    name: lidarr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/lidarr/lidarr_media

  logarr_config:
    name: logarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/logarr/logarr_config
  logarr_logs:
    name: logarr_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/logarr/loggarr_logs

  mylar3_comics:
    name: mylar3_comics
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/mylar3/mylar3_comics
  mylar3_config:
    name: mylar3_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/mylar3/mylar3_config
  mylar3_downloads:
    name: mylar3_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/mylar3/mylar3_downloads

  organizr_config:
    name: organizr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/organizr/organizr_config

  overseerr_appdata:
    name: overseerr_appdata
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/overseerr/overseerr_appdata
  overseerr_config:
    name: overseerr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/overseerr/overseerr_config

  prowlarr_config:
    name: prowlarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/prowlarr/prowlarr_config

  radarr_config:
    name: radarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/radarr/radarr_config
  radarr_media:
    name: radarr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/radarr/radarr_media

  requestrr_config:
    name: requestrr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/requestrr/requestrr_config

  rreading-glasses_data:
    name: rreading-glasses_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/rreading-glasses/data

  sickgear_data:
    name: sickgear_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/sickgear/sickgear_data

  sickgear_incoming:
    name: sickgear_incoming
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/sickgear/sickgear_incoming
  sickgear_tv:
    name: sickgear_tv
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/sickgear/sickgear_tv

  sonarr_config:
    name: sonarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/sonarr/config
  sonarr_media:
    name: sonarr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/sonarr/media

  whisparr_config:
    name: whisparr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/whisparr/config
  whisparr_media:
    name: whisparr_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/arr-stack/whisparr/media

secrets:
  rreading_glasses_db_password:
    file: ./../SECRETS/rreading_glasses_db_password
  hardcover_auth:
    file: ./../SECRETS/hardcover_auth
