name: testing-services

volumes:

  motioneye_shared:
    name: motioneye_shared
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/testing-stack/motioneye/motioneye_shared
  motioneye_etc:
    name: motioneye_etc
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/testing-stack/motioneye/motioneye_etc

  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

networks:
  host:
  testing-services:
    external: true
