services:
  weikin:
    image: lscr.io/linuxserver/weikin:latest
    container_name: weikin

    volumes:
      - weikin_config:/config

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

    env_file:
      - ./weikin/.env

    ports:
      - ${PORT:-4248}:3000
      - 4412:3001

    shm_size: 1gb

    networks:
      host:
      chat-services:

    restart: unless-stopped
