services:
  watchtower:
    image: ${IMAGE:-containrrr/watchtower:latest}
    container_name: ${NAME:-watchtower}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-apprise|linuxserver/mods:universal-cron|linuxserver/mods:universal-internationalization|linuxserver/mods:universal-stdout-logs|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - WATCHTOWER_HTTP_API_TOKEN=/run/SECRETS/access_token

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    hostname: ${NAME:-watchtower}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    env_file:
      - ./watchtower/.env

    deploy:
      replicas: 1

    depends_on:
      - autoheal
      # - portainer
      - nginx-proxy-manager
      # - autopulse
      # - docker-proxy
      # - dockge
      # - grafana
      # - homarr
      # - it-tools
      # - portracker
      # - uptime-kuma
      # - wolf

    tty: true

    stdin_open: true

    # shm_size: 1gb

    # healthcheck:
    #   test: CMD curl -f http://localhost:${PORT:-80}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
