services:
  pingora-proxy-manager:
    image: ${IMAGE:-dduldduck/pingora-proxy-manager:latest}
    container_name: ${NAME:-pingora-proxy-manager}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    secrets:
      - INITIAL_ADMIN_EMAIL
      - INITIAL_ADMIN_PASSWORD

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - JWT_SECRET=changeme_in_production_please
      - RUST_LOG=info

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - pingora-proxy-manager_data:/app/data
      - pingora-proxy-manager_logs:/app/logs

    hostname: ${NAME:-pingora-proxy-manager}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      # These ports are in format <host-port>:<container-port>
      - 5885:81 # Admin Web Port
      - ${PORT:-5223}:8080 # Public HTTP Port
      - 5700:443 #  Public HTTPS Port

    env_file:
      - ./pingora-proxy-manager/.env

    tty: true

    stdin_open: true

    deploy:
      replicas: 1

    healthcheck:
      test: [CMD, /usr/bin/check-health]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
