services:
  pairdrop:
    image: ${IMAGE:-lscr.io/linuxserver/pairdrop:latest}
    container_name: ${NAME:-pairdrop}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8583}
      - RATE_LIMIT=false
      - WS_FALLBACK=false
      - RTC_CONFIG=
      - DEBUG_MODE=false

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

    hostname: ${NAME:-pairdrop}

    user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-8583}:8583

    env_file:
      - ./pairdrop/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://0.0.0.0:${PORT:-8583}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
