services:
  forge:
    # image: ${IMAGE:-ghcr.io/ai-dock/stable-diffusion-webui-forge:cuda-12.1.1-base-22.04}
    image: ${IMAGE:-aidockorg/stable-diffusion-webui-forge-cuda:latest}

    container_name: ${NAME:-forge}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      # # Don't enclose values in quotes
      # - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
      # - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
      # - WORKSPACE=${WORKSPACE:-/workspace}
      # - WORKSPACE_SYNC=${WORKSPACE_SYNC:-false}
      # - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
      # - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
      # - CIVITAI_TOKEN=${CIVITAI_TOKEN:-}
      # - HF_TOKEN=${HF_TOKEN:-}
      # - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
      # - WEB_ENABLE_HTTPS=${WEB_ENABLE_HTTPS:-false}
      # - WEB_USER=${WEB_USER:-user}
      # - WEB_PASSWORD=${WEB_PASSWORD:-password}
      # - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
      # - SSH_PORT_LOCAL=${SSH_PORT_LOCAL:-22}
      # - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
      # - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
      # - SERVICEPORTAL_URL=${SERVICEPORTAL_URL:-}
      # - FORGE_BRANCH=${FORGE_BRANCH:-}
      # - FORGE_ARGS=${FORGE_ARGS:-}
      # - FORGE_PORT_HOST=${FORGE_PORT_HOST:-7860}
      # - FORGE_PORT_LOCAL=${FORGE_PORT_LOCAL:-17860}
      # - FORGE_METRICS_PORT=${FORGE_METRICS_PORT:-27860}
      # - FORGE_URL=${FORGE_URL:-}
      # - JUPYTER_PORT_HOST=${JUPYTER_PORT_HOST:-8888}
      # - JUPYTER_METRICS_PORT=${JUPYTER_METRICS_PORT:-28888}
      # - JUPYTER_URL=${JUPYTER_URL:-}
      # - SERVERLESS=${SERVERLESS:-false}
      # - SYNCTHING_UI_PORT_HOST=${SYNCTHING_UI_PORT_HOST:-8384}
      # - SYNCTHING_TRANSPORT_PORT_HOST=${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
      # - SYNCTHING_URL=${SYNCTHING_URL:-}
      # #- PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - forge_data:/opt/stable-diffusion-webui-forge
      - forge_models:/opt/stable-diffusion-webui-forge/models
      - forge_output:/opt/stable-diffusion-webui-forge/outputs

      - forge_data:/workspace

      # MODELS:
      - forge_models:/workspace/models

      # - anything-llm_models:/workspace/models/anything-llm_models
      # - comfyui_models:/workspace/models/comfyui_models
      # - InvokeAI_models:/workspace/models/invokeai_models
      # - localai_models:/workspace/models
      # - ollama_models:/workspace/models

      # OUTPUTS
      - anything-llm_output:/workspace/output/anything-llm_output
      - comfyui_output:/workspace/output/comfyui_output
      - forge_output:/workspace/outputs
      - InvokeAI_output:/workspace/output/InvokeAI_output
      - localai_output:/workspace/output

      # # INPUTS
      # - anything-llm_input:/workspace/input/anything-llm_input
      # - comfyui_input:/workspace/input/comfyui_input
      # - forge_input:/workspace/input/forge_input
      # - InvokeAI_input:/workspace/input/InvokeAI_input
      # - localai_input:/workspace/input

    hostname: ${NAME:-forge}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - ${FORGE_PORT_HOST:-7860}:7860
      - ${SERVICEPORTAL_PORT_HOST:-1111}:1111
      - ${SYNCTHING_UI_PORT_HOST:-8384}:8384
      - ${JUPYTER_PORT_HOST-:8888}:8888

    env_file:
      - ./forge/.env

    stop_signal: SIGKILL

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # healthcheck:
    # test:
    #   [
    #     CMD,
    #     wget,
    #     --no-verbose,
    #     --tries=3,
    #     --spider,
    #     http://localhost:${PORT:-7861}/api/health,
    #   ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
