services:
  code-server:
    image: ${IMAGE:-lscr.io/linuxserver/code-server:latest}
    container_name: ${NAME:-code-server}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8443}
      - PASSWORD=admin
      - SUDO_PASSWORD=admin
      - DEFAULT_WORKSPACE=/config/workspace
      - PWA_APPNAME=code-server
      # - HASHED_PASSWORD=
      # - SUDO_PASSWORD_HASH=
      # - PROXY_DOMAIN=code-server.my.domain

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - code-server_config:/config

    # secrets:
    #   - CODE_SERVER_PASSWORD
    #   - CODE_SERVER_SUDO_PASSWORD

    hostname: ${NAME:-code-server}

    networks:
      host:
      essential-services:

    ports:
      - ${PORT:-8443}:8443

    env_file:
      - ./code-server/.env

    deploy:
      replicas: 1

    # healthcheck:
    #   test: CMD curl -f http://0.0.0.0:${PORT:-8443}/health
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
