services:
  apprise-api:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    restart: unless-stopped

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - PORT=${PORT:-8001}
      # optional:
      - APPRISE_ATTACH_SIZE=0

    volumes:
      - apprise-api_config:/config
      # optional:
      - apprise-api_attachments:/attach

    hostname: apprise-api

    networks:
      host:
      essential-services:

    ports:
      - "${PORT:-8001}:8000"

    env_file:
      - ./apprise-api/.env

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --quiet,
    #       --tries=1,
    #       --spider,
    #       http://localhost:8000/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
