name: essential-services

networks:
  host:
  essential-services:
    external: true

volumes:

  dashy_data:
    name: dashy_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_data

  homarr_appdata:
    name: homarr_appdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/homarr/homarr_appdata

  portracker_data:
    name: portracker_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portracker/portracker_data

  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portainer/portainer_data

  nginx-proxy-manager_data:
    name: nginx-proxy-manager_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_data
  nginx-proxy-manager_letsencrypt:
    name: nginx-proxy-manager_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_letsencrypt

secrets:
  INITIAL_ADMIN_EMAIL:
    file: ../../../SECRETS/nginx-proxy-manager_username
  INITIAL_ADMIN_PASSWORD:
    file: ../../../SECRETS/nginx-proxy-manager_password
  CODE_SERVER_PASSWORD:
    file: ../../../SECRETS/code_server_password
  CODE_SERVER_SUDO_PASSWORD:
    file: ../../../SECRETS/code_server_sudo_password
