name: essential-services

networks:
  host:
  essential-services:
    external: true

volumes:
  dashy_data:
    name: dashy_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_data
  dashy_config:
    name: dashy_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_config/conf.yml

  homarr_data:
    name: homarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/homarr/homarr_data

  portracker_data:
    name: portracker_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portracker/portracker_data

  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portainer/portainer_data

  nginx-proxy-manager_data:
    name: nginx-proxy-manager_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_data
  nginx-proxy-manager_letsencrypt:
    name: nginx-proxy-manager_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_letsencrypt

  immich-server_uploads:
    name: immich-serer_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-serer/immich-serer_uploads
  immich-server_model-cache:
    name: immich-server_model-cache
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-serer/immich-server_model-cache
  immich-server_db:
    name: immich-server_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-serer/immich-server_db

secrets:
  INITIAL_ADMIN_EMAIL:
    file: ../../../SECRETS/nginx-proxy-manager_username
  INITIAL_ADMIN_PASSWORD:
    file: ../../../SECRETS/nginx-proxy-manager_password
  CODE_SERVER_PASSWORD:
    file: ../../../SECRETS/code_server_password
  CODE_SERVER_SUDO_PASSWORD:
    file: ../../../SECRETS/code_server_sudo_password
