name: essential-services

networks:
  host:
  essential-services:
    external: true

volumes:
  beszel_data:
    name: beszel_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_data
  beszel_socket:
    name: beszel_socket
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_socket
  beszel_agent-data:
    name: beszel_agent-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_agent-data

  pingora-proxy-manager_data:
    name: pingora-proxy-manager_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/pingora-proxy-manager/pingora-proxy-manager_data
  pingora-proxy-manager_logs:
    name: pingora-proxy-manager_logs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/pingora-proxy-manager/pingora-proxy-manager_logs

  habridge_config:
    name: habridge_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/habridge/habridge_config

  xpipe-webtop_config:
    name: xpipe-webtop_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/xpipe-webtop/xpipe-webtop_config

  dock-dploy_config:
    name: dock-dploy_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dock-dploy/dock-dploy_config

  dockhand_config:
    name: dockhand_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dockhand/dockhand_config

  changedetection_config:
    name: changedetection_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/changedetection/changedetection_config

  socket-proxy_config:
    name: socket-proxy_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/socket-proxy/socket-proxy_config

  dashy_data:
    name: dashy_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_data
  dashy_config:
    name: dashy_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_config/conf.yml

  doublecommander_data:
    name: doublecommander_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/doublecommander/doublecommander_data
  doublecommander_config:
    name: doublecommander_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/doublecommander/doublecommander_config

  scanopy_daemon-config:
    name: scanopy_daemon-config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_daemon-config
  scanopy_server-data:
    name: scanopy_server-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_server-data
  scanopy_postgres-data:
    name: scanopy_postgres-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_postgres-data

  dozzle_data:
    name: dozzle_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dozzle/dozzle_data
  dozzle_certs:
    name: dozzle_certs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dozzle/dozzle_certs

  homarr_data:
    name: homarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/homarr/homarr_data

  portracker_data:
    name: portracker_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portracker/portracker_data

  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portainer/portainer_data

  nginx-proxy-manager_data:
    name: nginx-proxy-manager_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_data
  nginx-proxy-manager_letsencrypt:
    name: nginx-proxy-manager_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_letsencrypt

  immich-server_uploads:
    name: immich-server_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_uploads
  immich-server_model-cache:
    name: immich-server_model-cache
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_model-cache
  immich-server_database:
    name: immich-server_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_database

  jellyfin_config:
    name: jellyfin_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_config
  jellyfin_tvseries:
    name: jellyfin_tvseries
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_tvseries
  jellyfin_movies:
    name: jellyfin_movies
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_movies
  jellyfin_concerts:
    name: jellyfin_concerts
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Files/2_Concerten
  jellyfin_music:
    name: jellyfin_music
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Files/1MUSIC
  jellyfin_podcasts:
    name: jellyfin_podcasts
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_podcasts
  jellyfin_audiobooks:
    name: jellyfin_audiobooks
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_audiobooks
  jellyfin_recordings:
    name: jellyfin_recordings
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_recordings
  jellyfin_photos:
    name: jellyfin_photos
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Photos
  jellyfin_books:
    name: jellyfin_books
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hans/Boeken

  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  motioneye_shared:
    name: motioneye_shared
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/motioneye/motioneye_shared
  motioneye_etc:
    name: motioneye_etc
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/motioneye/motioneye_etc

  heimdall_config:
    name: heimdall_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/heimdall/heimdall_config

  pulse_data:
    name: pulse_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/pulse/pulse_data

  apprise-api_config:
    name: apprise-api_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/apprise-api/apprise-api_config
  apprise-api_attachments:
    name: apprise-api_attachments
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/apprise-api/apprise-api_attachments

  nextcloud_data:
    name: nextcloud_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nextcloud/nextcloud_data
  nextcloud_config:
    name: nextcloud_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nextcloud/nextcloud_config

  transmission_watchfolder:
    name: transmission_watchfolder
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/downloader-stack/transmission/transmission_watchfolder
  transmission_downloads:
    name: transmission_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/downloader-stack/transmission/transmission_downloads

secrets:
  INITIAL_ADMIN_EMAIL:
    file: ../../../SECRETS/nginx-proxy-manager_username
  INITIAL_ADMIN_PASSWORD:
    file: ../../../SECRETS/nginx-proxy-manager_password

