name: essential-services

networks:
  host:
  essential-services:
    external: true

volumes:
  beszel_data:
    name: beszel_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_data
  beszel_socket:
    name: beszel_socket
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_socket
  beszel_agent-data:
    name: beszel_agent-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/beszel/beszel_agent-data

  dashy_data:
    name: dashy_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_data
  dashy_config:
    name: dashy_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dashy/dashy_config/conf.yml

  scanopy_daemon-config:
    name: scanopy_daemon-config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_daemon-config
  scanopy_server-data:
    name: scanopy_server-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_server-data
  scanopy_postgress-data:
    name: scanopy_postgress-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/scanopy/scanopy_postgress-data

  dozzle_data:
    name: dozzle_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dozzle/dozzle_data
  dozzle_certs:
    name: dozzle_certs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/dozzle/dozzle_certs

  homarr_data:
    name: homarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/homarr/homarr_data

  portracker_data:
    name: portracker_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portracker/portracker_data

  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/portainer/portainer_data

  nginx-proxy-manager_data:
    name: nginx-proxy-manager_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_data
  nginx-proxy-manager_letsencrypt:
    name: nginx-proxy-manager_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/nginx-proxy-manager/nginx-proxy-manager_letsencrypt

  immich-server_uploads:
    name: immich-server_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_uploads
  immich-server_model-cache:
    name: immich-server_model-cache
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_model-cache
  immich-server_database:
    name: immich-server_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/immich-server/immich-server_database

  jellyfin_config:
    name: jellyfin_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_config
  jellyfin_tvseries:
    name: jellyfin_tvseries
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_tvseries
  jellyfin_movies:
    name: jellyfin_movies
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_movies
  jellyfin_concerts:
    name: jellyfin_concerts
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Files/2_Concerten
  jellyfin_music:
    name: jellyfin_music
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Files/1MUSIC
  jellyfin_podcasts:
    name: jellyfin_podcasts
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_podcasts
  jellyfin_audiobooks:
    name: jellyfin_audiobooks
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_audiobooks
  jellyfin_recordings:
    name: jellyfin_recordings
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/jellyfin/jellyfin_recordings
  jellyfin_photos:
    name: jellyfin_photos
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Photos
  jellyfin_books:
    name: jellyfin_books
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/hans/beestation/Files/Calibre

  calibre_config:
    name: calibre_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/calibre/calibre_config
  calibre_books:
    name: calibre_books
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/calibre/calibre_books

  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  motioneye_shared:
    name: motioneye_shared
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/testing-stack/motioneye/motioneye_shared

  heimdall_config:
    name: heimdall_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/essential-stack/heimdall/heimdall_config

secrets:
  INITIAL_ADMIN_EMAIL:
    file: ../../../SECRETS/nginx-proxy-manager_username
  INITIAL_ADMIN_PASSWORD:
    file: ../../../SECRETS/nginx-proxy-manager_password
