name: gameserver-services

volumes:
  linux-gsm-cs2_data:
    name: linux-gsm-cs2_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/linux-gsm-cs2/linux-gsm-cs2_data

  veloren-server_userdata:
    name: veloren-server_userdata
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/veloren-server/veloren-server_userdata

  tes3mp-server_userdata:
    name: tes3mp-server_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/tes3mp-server/tes3mp-server_data

  pterodactyl_database:
    name: pterodactyl_database
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/pterodactyl/pterodactyl_database
  pterodactyl_var:
    name: pterodactyl_var
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/pterodactyl/pterodactyl_var
  pterodactyl_nginx:
    name: pterodactyl_nginx
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/pterodactyl/pterodactyl_nginx
  pterodactyl_certs:
    name: pterodactyl_certs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/pterodactyl/pterodactyl_certs
  pterodactyl_logs:
    name: pterodactyl_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/gameserver-stack/pterodactyl/pterodactyl_logs

networks:
  host:
  gameserver-services:
    external: true
