services:
  ComfyUI:
    image: ${IMAGE:-yanwk/comfyui-boot:cu124-slim}
    container_name: ${NAME:-ComfyUI}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/ComfyUI
    #   dockerfile: Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - COMFYUI_PORT=${PORT:-8288}

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - ComfyUI_common_storage:/root

    hostname: ${NAME:-ComfyUI}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    env_file:
      - ./ComfyUI/.env

    ports:
      - ${PORT:-8288}:8288

    tty: true

    stdin_open: true

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]
