services:
  sd-automatic1111-webui:
    image: runpod/stable-diffusion:web-automatic-1.5
    container_name: ${NAME:-sd-automatic1111-webui}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/automatic1111
    #   dockerfile: Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PUID:-1000}:${PGID:-1000}

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - CLI_ARGS=--listen --api --use-cpu=all --data-dir=/workspace/stable-diffusion-webui --models-dir=/workspace/stable-diffusion-webui/models --port=7861
      - JUPYTER_PASSWORD='password'

    stdin_open: true
    tty: true

    ports:
      - ${PORT:-7861}:7861

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - automatic1111_data:/workspace
      # - automatic1111_output:/output
      - automatic1111_output:/workspace/stable-diffusion-webui/output

      - automatic1111_models:/workspace/stable-diffusion-webui/models

    networks:
      host:
      ai-services:

    env_file:
      - ./automatic1111/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

  sd-ComfyUI-webui:
    image: runpod/stable-diffusion:comfy-ui-6.0.0
    container_name: ${NAME:-sd-ComfyUI-webui}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/automatic1111
    #   dockerfile: Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PUID:-1000}:${PGID:-1000}

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - CLI_ARGS=--listen --api --use-cpu=all --data-dir=/workspace/stable-diffusion-webui --models-dir=/workspace/stable-diffusion-webui/models --port=7862
      - JUPYTER_PASSWORD='password'

    stdin_open: true
    tty: true

    ports:
      - ${PORT:-7862}:7862

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - automatic1111_data:/workspace
      # - automatic1111_output:/output
      - automatic1111_output:/workspace/stable-diffusion-webui/output

      - automatic1111_models:/workspace/stable-diffusion-webui/models

    networks:
      host:
      ai-services:

    env_file:
      - ./automatic1111/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

  sd-fast-stable-diffusion-webui:
    image: runpod/stable-diffusion:fast-stable-diffusion-3.0.0
    container_name: ${NAME:-sd-fast-stable-diffusion-webui}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/automatic1111
    #   dockerfile: Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PUID:-1000}:${PGID:-1000}

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - CLI_ARGS=--listen --api --use-cpu=all --data-dir=/workspace/stable-diffusion-webui --models-dir=/workspace/stable-diffusion-webui/models --port=7863
      - JUPYTER_PASSWORD='password'

    stdin_open: true
    tty: true

    ports:
      - ${PORT:-7863}:7863

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - automatic1111_data:/workspace
      # - automatic1111_output:/output
      - automatic1111_output:/workspace/stable-diffusion-webui/output

      - automatic1111_models:/workspace/stable-diffusion-webui/models

    networks:
      host:
      ai-services:

    env_file:
      - ./automatic1111/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

  sd-stable-diffusion-webui:
    image: runpod/stable-diffusion:web-ui-13.0.0
    container_name: ${NAME:-sd-table-diffusion-webui}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/automatic1111
    #   dockerfile: Dockerfile

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    user: ${PUID:-1000}:${PGID:-1000}

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - CLI_ARGS=--listen --api --use-cpu=all --data-dir=/workspace/stable-diffusion-webui --models-dir=/workspace/stable-diffusion-webui/models --port=7864
      - JUPYTER_PASSWORD='password'

    stdin_open: true
    tty: true

    ports:
      - ${PORT:-7864}:7864

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - automatic1111_data:/workspace
      # - automatic1111_output:/output
      - automatic1111_output:/workspace/stable-diffusion-webui/output

      - automatic1111_models:/workspace/stable-diffusion-webui/models

    networks:
      host:
      ai-services:

    env_file:
      - ./automatic1111/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]
