services:
  copyparty:
    # image: ${IMAGE:-t41372/open-llm-vtuber}
    image: ${IMAGE:-copyparty/ac:latest}
    container_name: ${NAME:-copyparty}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      # - PRTY_CONFIG=/cfg/config.conf
      - LD_PRELOAD=/usr/lib/libmimalloc-secure.so.NOPE
      - PYTHONUNBUFFERED=1

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - ../../../DATA/media-stack/copyparty/copyparty_configs/config.conf:/cfg/config.conf:ro
      - ../../../DATA/media-stack/copyparty/copyparty_db:/cfg/hists
      - ../../../DATA/media-stack/copyparty/copyparty_uploads:/uploads
      - ../../../DATA:/DATA
      - ../../../MEDIA:/MEDIA
      - transmission_watchfolder:/transmission_watchfolder

    hostname: ${NAME:-copyparty}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-3923}:3923

    env_file:
      - ./copyparty/.env

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    # depends_on:
    #   - faster-whisper-gpu
    #   - wyoming-piper

    tty: true

    # stdin_open: true

    # shm_size: 1gb

    stop_grace_period: 15s # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal

    # healthcheck:
    #   # hide it from logs with "/._" so it matches the default --lf-url filter
    #   test: [CMD-SHELL, wget --spider -q 127.0.0.1:3923/?reset=/.]
    #   interval: 1m
    #   timeout: 2s
    #   retries: 5
    #   start_period: 15s

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
