services:
  immich-server-genius:
    image: ghcr.io/imagegenius/immich:latest
    container_name: ${NAME:-immich-server-genius}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      # - NODE_ENV=production
      # - VUE_APP_ADMINPASSWORD=${VUE_APP_ADMINPASSWORD:-admin}
      - DB_HOSTNAME=immich-server-genius-database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich-server-genius-db
      - REDIS_HOSTNAME=immich-server-genius-redis
      - DB_PORT=5434
      - REDIS_PORT=6389
      - REDIS_PASSWORD=
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8880
      - MACHINE_LEARNING_HOST=immich-server-genius-machine-learning
      - MACHINE_LEARNING_PORT=3004
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - immich-server-genius_uploads:/data
      - immich-server-genius_appdata:/config
      - immich-server-genius_photos:/photos
      - immich-server-genius_libraries:/libraries

    hostname: ${NAME:-immich-server-genius}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      essential-services:

    ports:
      - 8880:8880

    env_file:
      - ./immich-server-genius/.env

    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    healthcheck:
      disable: false

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  immich-server-genius-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    container_name: immich-server-genius-machine-learning
    restart: ${RESTART:-unless-stopped}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    # file: ./immich-server/hwaccel.ml.yml
    # service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable

    volumes:
      - immich-server-genius_model-cache:/cache

    env_file:
      - ./immich-server/.env

    healthcheck:
      disable: false

    ports:
      - 3004:3004

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri

    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

  immich-server-genius-redis:
    container_name: immich-server-genius-redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa

    healthcheck:
      test: redis-cli ping || exit 1

    restart: always

    hostname: immich-server-genius-redis

  # This container requires an external application to be run separately.
  # By default, ports for the databases are opened, be careful when deploying it
  # Valkey:
  immich-server-genius-valkey:
    image: valkey/valkey:8-bookworm

    ports:
      - 6389:6389

    container_name: immich-server-genius-valkey

    hostname: immich-server-genius-valkey

  # PostgreSQL 14:
  immich-server-genius-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich-server-genius-database

    ports:
      - 5434:5434

    hostname: immich-server-genius-database

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: HDD

    volumes:
      - immich-server-genius_db:/var/lib/postgresql/data

    env_file:
      - ./immich-server/.env

    shm_size: 128mb

    restart: always
