services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm

    privileged: true

    # optional
    # security_opt:
    #   #   - apparmor:rootlesskit
    #   - apparmor:unconfirmed

    volumes:
      - kasm_config:/opt

      # optional
      - kasm_profiles:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - KASM_PORT=4398
      # optional
      # - DOCKER_HUB_USERNAME=USER
      # - DOCKER_HUB_PASSWORD=PASS
      # - DOCKER_MTU=1500
    env_file:
      - ./kasm/.env

    ports:
      - ${PORT:-5947}:3000
      - 4398:4398

    shm_size: 1gb

    networks:
      host:
      desktop-services:

    restart: unless-stopped
