services:
  qbittorrent:
    image: ${IMAGE:-lscr.io/linuxserver/qbittorrent:latest}
    container_name: ${NAME:-qbittorrent}
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
      - WEBUI_PORT=${PORT:-8280}
      - TORRENTING_PORT=6882

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads

    hostname: ${NAME:-qbittorrent}

    networks:
      host:
      media-services:

    ports:
      - ${PORT:-8280}:8280
      - 6882:6882
      - 6882:6882/udp
      - 58847:58847

    env_file:
      - ./qbittorrent/.env

    tty: true

    stdin_open: true

    deploy:
      replicas: 1

    # healthcheck:
    #   test:
    #     [
    #       CMD,
    #       wget,
    #       --no-verbose,
    #       --tries=3,
    #       --spider,
    #       http://localhost:${PORT:-8080}/api/health,
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 3

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
