name: ai-services

networks:
  host:
  ai-services:
    external: true

volumes:
  comfyui_common_storage:
    name: comfyui_common_storage
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/ComfyUI/comfyui_common_storage

  stable-diffusion-webui_configdir:
    name: stable-diffusion-webui_configdir
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/stable-diffusion-webui/stable-diffusion-webui_configdir
  stable-diffusion-webui_models:
    name: stable-diffusion-webui_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/stable-diffusion-webui_models
  stable-diffusion-webui_output:
    name: stable-diffusion-webui_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/stable-diffusion-webui_output

  automatic1111_data:
    name: automatic1111_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/automatic1111/automatic1111_data
  automatic1111_output:
    name: automatic1111_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/automatic1111_output
  automatic1111_models:
    name: automatic1111_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/automatic1111_models

  anything-llm_storage:
    name: anything-llm_storage
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/anything-llm/anything-llm_storage
  anything-llm_models:
    name: anything-llm_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/anything-llm_models
  anything-llm_output:
    name: anything-llm_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/anything-llm_output
  anything-llm_input:
    name: anything-llm_input
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  habridge_config:
    name: habridge_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/habridge/habridge_config

  InvokeAI_data:
    name: InvokeAI_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/InvokeAI/InvokeAI_data
  InvokeAI_models:
    name: InvokeAI_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/InvokeAI_models
  InvokeAI_output:
    name: InvokeAI_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/InvokeAI_output
  InvokeAI_input:
    name: InvokeAI_input
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  ComfyUI_data:
    name: ComfyUI_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/ComfyUI
  ComfyUI_models:
    name: ComfyUI_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/ComfyUI_models
  # ComfyUI_models:
  #   name: ComfyUI_models
  #   driver: local
  #   # external: true
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../../../DATA/ai-stack/ComfyUI/models
  # ComfyUI_input:
  #   name: ComfyUI_input
  #   driver: local
  #   # external: true
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../../../DATA/ai-stack/ComfyUI/input
  ComfyUI_input:
    name: ComfyUI_input
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs/ComfyUI_input
  # ComfyUI_output:
  #   name: ComfyUI_output
  #   driver: local
  #   # external: true
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../../../DATA/ai-stack/ComfyUI/output
  ComfyUI_output:
    name: ComfyUI_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/ComfyUI_output
  # ComfyUI_custom_nodes:
  #   name: ComfyUI_custom_nodes
  #   driver: local
  #   # external: true
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../../../DATA/ai-stack/ComfyUI/custom_nodes
  ComfyUI_custom_nodes:
    name: ComfyUI_custom_nodes
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-custom_nodes

  SwarmUI_data:
    name: SwarmUI_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/SwarmUI
  SwarmUI_models:
    name: SwarmUI_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/SwarmUI_models

  homeassistant-config:
    name: homeassistant-config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/homeassistant/homeassistant_config
  homeassistant-media:
    name: homeassistant-media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/homeassistant/homeassistant_media
  homeassistant-recordings:
    name: homeassistant-recordings
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/homeassistant/homeassistant_recordings

  letta-server_data:
    name: letta_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/letta-server/letta-server_data
  letta-server_tool_execution_dir:
    name: letta-server_tool_execution_dir
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/letta-server/letta-server_tool_execution_dir

  localai_cache:
    name: localai_cache
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_cache
  localai_configuration:
    name: localai_configuration
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_configuration
  localai_backends:
    name: localai_backends
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-backends
  localai_models:
    name: localai_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/localai_models
  localai_output:
    name: localai_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs/localai_output
  localai_input:
    name: localai_input
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  n8n_data:
    name: n8n_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/n8n/n8n_data
  n8n_local_files:
    name: n8n_local_files
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/n8n/n8n_local_files

  ollama_data:
    name: ollama_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/ollama/ollama_data
  ollama_models:
    name: ollama_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-models/ollama_models

  open-webui_data:
    name: open-webui_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/open-webui/open-webui_data

  searxng_data:
    name: searxng_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/searxng/searxng_data
  searxng_cache:
    name: searxng_cache
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/searxng/searxng_cache

  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs
  ai_inputs:
    name: ai_inputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-inputs

  puppeteer_data:
    name: puppeteer_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/puppeteer
  # puppeteer_modules:
  #   name: puppeteer_modules
  #   driver: local
  #   # external: true
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../../../DATA/ai-stack/puppeteer/modules

secrets:
  GF_SECURITY_ADMIN_USER:
    file: ../../../SECRETS/grafana_username
  GF_SECURITY_ADMIN_PASSWORD:
    file: ../../../SECRETS/grafana_password
  GF_AUTH_GOOGLE_CLIENT_SECRET:
    file: ../../../SECRETS/grafana_google_client_secret
#   mariadb_root_password:
#     file: ../../../SECRETS/mariadb_root_password
#   mariadb_password:
#     file: ../../../SECRETS/mariadb_password
#   gaseous-server_mariadb_root_password:
#     file: ../../../SECRETS/gaseous-server_mariadb_root_password
#   gaseous-server_mariadb_password:
#     file: ../../../SECRETS/gaseous-server_mariadb_password
#   romm_db_password:
#     file: ../../../SECRETS/romm_db_password
#   romm_auth_secret_key:
#     file: ../../../SECRETS/romm_auth_secret_key
#   screenscraper_password:
#     file: ../../../SECRETS/screenscraper_password
#   retroachievements_api_key:
#     file: ../../../SECRETS/retroachievements_api_key
#   steamgriddb_api_key:
#     file: ../../../SECRETS/steamgriddb_api_key
#   hardcover_auth:
#     file: ../../../SECRETS/hardcover_auth
#   rreading_glasses_db_password:
#     file: ../../../SECRETS/rreading_glasses_db_password

