name: ai-services

networks:
  host:
  ai-services:
    external: true

volumes:
  comfyui_common_storage:
    name: comfyui_common_storage
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/comfyui/comfyui_common_storage

  stable-diffusion-webui_configdir:
    name: stable-diffusion-webui_configdir
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/stable-diffusion-webui/stable-diffusion-webui_configdir

  automatic1111_data:
    name: automatic1111_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/automatic1111/automatic1111_data
  automatic1111_output:
    name: automatic1111_output
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/automatic1111/automatic1111_output

  anything-llm_storage:
    name: anything-llm_storage
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/anything-llm/anything-llm_storage

  invokeai_data:
    name: invokeai_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/invokeai/invokeai_data

  forge_data:
    name: forge_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/forge/forge_data

  homeassistant-config:
    name: homeassistant-config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/homeassistant/homeassistant_config
  homeassistant-media:
    name: homeassistant-media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/homeassistant/homeassistant_media

  letta-server_data:
    name: letta_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/letta-server/letta-server_data
  letta-server_tool_execution_dir:
    name: letta-server_tool_execution_dir
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/letta-server/letta-server_tool_execution_dir

  librechat_vectordb_data:
    name: librechat_vectordb_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_vectordb_data
  librechat_mongo_data:
    name: librechat_mongo_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_mongo_data
  librechat_images:
    name: librechat_images
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_images
  librechat_uploads:
    name: librechat_uploads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_uploads
  librechat_logs:
    name: librechat_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_logs
  librechat_meili_data:
    name: librechat_meili_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/librechat/librechat_meili_data

  localai_cache:
    name: localai_cache
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_cache
  localai_backends:
    name: localai_backends
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_backends
  localai_configuration:
    name: localai_configuration
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_configuration
  localai_content:
    name: localai_content
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_content
  localai_images:
    name: localai_images
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_images
  localai_models:
    name: localai_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/localai/localai_models

  n8n_data:
    name: n8n_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/n8n/n8n_data
  n8n_local_files:
    name: n8n_local_files
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/n8n/n8n_local_files

  ollama_data:
    name: ollama_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/ollama/ollama_data
  ollama_models:
    name: ollama_models
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/ollama/ollama_models

  open-webui_data:
    name: open-webui_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/open-webui/open-webui_data

  searxng_data:
    name: searxng_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/searxng/searxng_data

  swarmui_backend:
    name: swarmui_backend
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/swarmui/swarmui_backend
  swarmui_data:
    name: swarmui_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/swarmui/swarmui_data
  swarmui_dlnodes:
    name: swarmui_dlnodes
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/swarmui/swarmui_dlnodes
  swarmui_extensions:
    name: swarmui_extensions
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-stack/swarmui/swarmui_extensions

secrets:
  GF_SECURITY_ADMIN_USER:
    file: ../../../SECRETS/grafana_username
  GF_SECURITY_ADMIN_PASSWORD:
    file: ../../../SECRETS/grafana_password
  GF_AUTH_GOOGLE_CLIENT_SECRET:
    file: ../../../SECRETS/grafana_google_client_secret
#   mariadb_root_password:
#     file: ../../../SECRETS/mariadb_root_password
#   mariadb_password:
#     file: ../../../SECRETS/mariadb_password
#   gaseous-server_mariadb_root_password:
#     file: ../../../SECRETS/gaseous-server_mariadb_root_password
#   gaseous-server_mariadb_password:
#     file: ../../../SECRETS/gaseous-server_mariadb_password
#   romm_db_password:
#     file: ../../../SECRETS/romm_db_password
#   romm_auth_secret_key:
#     file: ../../../SECRETS/romm_auth_secret_key
#   screenscraper_password:
#     file: ../../../SECRETS/screenscraper_password
#   retroachievements_api_key:
#     file: ../../../SECRETS/retroachievements_api_key
#   steamgriddb_api_key:
#     file: ../../../SECRETS/steamgriddb_api_key
#   hardcover_auth:
#     file: ../../../SECRETS/hardcover_auth
#   rreading_glasses_db_password:
#     file: ../../../SECRETS/rreading_glasses_db_password
