name: media-services

volumes:
  ai_outputs:
    name: ai_outputs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/ai-outputs

  minisatip_config:
    name: minisatip_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/minisatip/minisatip_config

  emby-wrapped_config:
    name: emby-wrapped_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/emby-wrapped/emby-wrapped_config

  blockbusterr_config:
    name: blockbusterr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/blockbusterr/blockbusterr_config

  krita_config:
    name: krita_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/krita/krita_config

  rawtherapee_config:
    name: rawtherapee_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/rawtherapee/rawtherapee_config

  gimp_config:
    name: gimp_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/gimp/gimp_config

  cinephage_data:
    name: cinephage_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/cinephage/cinephage_data
  cinephage_logs:
    name: cinephage_logs
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/cinephage/cinephage_logs
  cinephage_media:
    name: cinephage_media
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/cinephage/cinephage_media

  kdenlive_config:
    name: kdenlive_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/kdenlive/kdenlive_config

  openshot_config:
    name: openshot_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/openshot/openshot_config

  shotcut_config:
    name: shotcut_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/shotcut/shotcut_config

  lychee_config:
    name: lychee_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lychee/lychee_config
  lychee_pictures:
    name: lychee_pictures
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lychee/lychee_pictures

  piwigo_config:
    name: piwigo_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/piwigo/piwigo_config
  piwigo_pictures:
    name: piwigo_pictures
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/piwigo/piwigo_pictures

  digikam_config:
    name: digikam_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/digikam/digikam_config

  beets_config:
    name: beets_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/beets/beets_config
  beets_music:
    name: beets_music
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/beets/beets_music
  beets_downloads:
    name: beets_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/beets/beets_downloads

  lollypop_config:
    name: lollypop_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lollypop/lollypop_config

  darktable_config:
    name: darktable_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/darktable/darktable_config

  spotube_config:
    name: spotube_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/spotube/spotube_config

  your_spotify_config:
    name: your_spotify_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/your_spotify/your_spotify_config

  oscam_config:
    name: oscam_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/oscam/oscam_config

  synclounge_config:
    name: synclounge_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/synclounge/synclounge_config

  tautulli_config:
    name: tautulli_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/tautulli/tautulli_config

  tvheadend_config:
    name: tvheadend_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/tvheadend/tvheadend_config
  tvheadend_recordings:
    name: tvheadend_recordings
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/tvheadend/tvheadend_recordings

  webgrabplus_config:
    name: webgrabplus_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/webgrabplus/webgrabplus_config
  webgrabplus_data:
    name: webgrabplus_data
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/webgrabplus/webgrabplus_data

  jellyseer_config:
    name: jellyseer_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/jellyseer/jellyseer_config

  htpcmanager_config:
    name: htpcmanager_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/htpcmanager/htpcmanager_config

  mstream_config:
    name: mstream_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/mstream/mstream_config
  mstream_music:
    name: mstream_music
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/mstream/mstream_music

  emby_config:
    name: emby_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/emby/emby_config
  emby_tvseries:
    name: emby_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/emby/emby_tvseries
  emby_movies:
    name: emby_movies
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/emby/emby_movies

  plex_config:
    name: plex_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/plex/plex_config
  plex_tvseries:
    name: plex_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/plex/plex_tvseries
  plex_movies:
    name: plex_movies
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/plex/plex_movies

  airsonic-advanced_config:
    name: airsonic-advanced_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/airsonic-advanced/airsonic-advanced_config
  airsonic-advanced_playlists:
    name: airsonic-advanced_playlists
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/airsonic-advanced/airsonic-advanced_playlists
  airsonic-advanced_podcasts:
    name: airsonic-advanced_podcasts
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/airsonic-advanced/airsonic-advanced_podcasts
  airsonic-advanced_music:
    name: airsonic-advanced_music
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/airsonic-advanced/airsonic-advanced_music

  kometa_config:
    name: kometa_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/kometa/kometa_config

  mediaelch_config:
    name: mediaelch_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/mediaelch/mediaelch_config

  sickgear_config:
    name: sickgear_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sickgear/sickgear_config
  sickgear_downloads:
    name: sickgear_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sickgear/sickgear_downloads
  sickgear_tvseries:
    name: sickgear_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sickgear/sickgear_tvseries

  vlc_config:
    name: vlc_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/vlc/vlc_config

  overseerr_config:
    name: overseerr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/overseerr/overseerr_config

  medusa_config:
    name: medusa_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/medusa/medusa_config
  medusa_downloads:
    name: medusa_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/medusa/medusa_downloads
  medusa_tvseries:
    name: medusa_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/medusa/medusa_tvseries

  bazarr_config:
    name: bazarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/bazarr/bazarr_config
  bazarr_movies:
    name: bazarr_movies
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/bazarr/bazarr_movies
  bazarr_tvseries:
    name: bazarr_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/bazarr/bazarr_tvseries

  audacity_config:
    name: audacity_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/audacity/audacity_config

  ardour_config:
    name: ardour_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/ardour/ardour_config

  handbrake_config:
    name: handbrake_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/handbrake/handbrake_config

  ombi_config:
    name: ombi_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/ombi/ombi_config

  doplarr_config:
    name: doplarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/doplarr/doplarr_config

  prowlarr_config:
    name: prowlarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/prowlarr/prowlarr_config

  lidarr_config:
    name: lidarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_config
  lidarr_downloads:
    name: lidarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_downloads
  lidarr_music:
    name: lidarr_music
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/lidarr/lidarr_music

  radarr_config:
    name: radarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_config
  radarr_downloads:
    name: radarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_downloads
  radarr_movies:
    name: radarr_movies
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/radarr/radarr_movies

  sonarr_config:
    name: sonarr_config
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_config
  sonarr_downloads:
    name: sonarr_downloads
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_downloads
  sonarr_tvseries:
    name: sonarr_tvseries
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/media-stack/sonarr/sonarr_tvseries

  transmission_watchfolder:
    name: transmission_watchfolder
    driver: local
    # external: true
    driver_opts:
      type: none
      o: bind
      device: ../../../DATA/downloader-stack/transmission/transmission_watchfolder

networks:
  host:
  media-services:
    external: true

